name: Build LaTeX document
on: 
  push:
    branches: [main]
    paths: ['src/**', '.github/workflows/**']
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Git repository
        uses: actions/checkout@v4  
        
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action@v2
        with:
          run: |
            cd src
            latexmk -pdf -interaction=nonstopmode -halt-on-error
            
      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: src/main.pdf

